export const siteConfig = {
  name: "AFCEN Project Marketplace",
  description:
    "A curated marketplace connecting climate-smart agricultural projects across Kenya with mission-aligned investors.",
  accent: "#10b981",
  nav: [
    { label: "Marketplace", href: "/" },
    { label: "Investor Dashboard", href: "/dashboard" },
    { label: "Admin Panel", href: "/admin" },
  ],
  hero: {
    title: "Invest in Kenya's climate-resilient agriculture pipeline.",
    subtitle:
      "Source vetted projects, track impact KPIs, and deploy capital where it matters most. AFCEN helps investors and project owners collaborate with confidence.",
    ctaPrimary: "Explore Projects",
    ctaSecondary: "Investor Onboarding",
  },
  stats: [
    { label: "Active Projects", value: "48" },
    { label: "Capital Seeking", value: "$38.6M" },
    { label: "Counties Covered", value: "21" },
    { label: "Impact Beneficiaries", value: "162K" },
  ],
  filters: {
    sectors: ["Agri-processing", "Irrigation", "AgTech", "Dairy", "Horticulture"],
    stages: ["Seed", "Series A", "Growth", "Expansion"],
    ticketSizes: ["<$250K", "$250K-$1M", "$1M-$5M", ">$5M"],
  },
  projects: [
    {
      id: "afcen-001",
      slug: "nyandarua-dairy-cold-chain",
      name: "Nyandarua Dairy Cold Chain",
      location: "Nyandarua County",
      sector: "Dairy",
      stage: "Growth",
      summary:
        "Solar-powered cold chain expansion for 12,000 smallholder dairy farmers.",
      fundingTarget: "$4.2M",
      equityOffer: "18% equity",
      impact: "Reduce post-harvest loss by 32%",
      tags: ["Climate-Smart", "Women-Led", "Export Ready"],
      timeline: "2025-2028",
      metrics: {
        irr: "18-22%",
        payback: "4.5 yrs",
        jobs: "1,200",
      },
    },
    {
      id: "afcen-002",
      slug: "kisumu-smart-irrigation",
      name: "Kisumu Smart Irrigation Hub",
      location: "Kisumu County",
      sector: "Irrigation",
      stage: "Series A",
      summary:
        "IoT-enabled irrigation network covering 2,800 hectares of rice and maize.",
      fundingTarget: "$6.5M",
      equityOffer: "22% equity",
      impact: "Water savings up to 41%",
      tags: ["IoT", "Climate Adaptation", "Smallholder"],
      timeline: "2025-2029",
      metrics: {
        irr: "20-25%",
        payback: "5.2 yrs",
        jobs: "1,850",
      },
    },
    {
      id: "afcen-003",
      slug: "meru-horticulture-export",
      name: "Meru Horticulture Export Park",
      location: "Meru County",
      sector: "Horticulture",
      stage: "Expansion",
      summary:
        "Packhouse modernization and export logistics for 5,400 growers.",
      fundingTarget: "$8.9M",
      equityOffer: "20% equity",
      impact: "Increase export revenues by 2.4x",
      tags: ["Export", "Cold Chain", "Youth Jobs"],
      timeline: "2024-2027",
      metrics: {
        irr: "17-21%",
        payback: "4.1 yrs",
        jobs: "2,300",
      },
    },
    {
      id: "afcen-004",
      slug: "nakuru-agri-processing",
      name: "Nakuru Agri-Processing Cluster",
      location: "Nakuru County",
      sector: "Agri-processing",
      stage: "Growth",
      summary:
        "Processing facility for potatoes and legumes with renewable energy retrofit.",
      fundingTarget: "$5.7M",
      equityOffer: "16% equity",
      impact: "Cut emissions by 28%",
      tags: ["Green Energy", "Value Addition"],
      timeline: "2025-2028",
      metrics: {
        irr: "19-23%",
        payback: "4.8 yrs",
        jobs: "1,540",
      },
    },
    {
      id: "afcen-005",
      slug: "turkana-climate-resilience",
      name: "Turkana Climate Resilience Farms",
      location: "Turkana County",
      sector: "AgTech",
      stage: "Seed",
      summary:
        "Regenerative agriculture pilots with drought-resilient crops and data analytics.",
      fundingTarget: "$2.3M",
      equityOffer: "12% equity",
      impact: "Improve soil carbon by 18%",
      tags: ["Regenerative", "Data-Led", "Pilot"],
      timeline: "2025-2026",
      metrics: {
        irr: "15-19%",
        payback: "5.8 yrs",
        jobs: "620",
      },
    },
  ],
  mapbox: {
    token: "pk.placeholder-token",
    pins: [
      { label: "Nyandarua", coordinates: "0.1808, 36.5229" },
      { label: "Kisumu", coordinates: "-0.0917, 34.7680" },
      { label: "Meru", coordinates: "0.0463, 37.6559" },
      { label: "Nakuru", coordinates: "-0.3031, 36.0800" },
      { label: "Turkana", coordinates: "3.3122, 35.5658" },
    ],
  },
  dashboard: {
    kpis: [
      { label: "Capital Committed", value: "$12.4M", delta: "+14% QoQ" },
      { label: "Active Term Sheets", value: "9", delta: "+3 this month" },
      { label: "Avg. IRR", value: "19.6%", delta: "+1.1%" },
      { label: "Impact Score", value: "8.7/10", delta: "Top quartile" },
    ],
    pipeline: [
      { month: "Jan", value: 4.2 },
      { month: "Feb", value: 5.1 },
      { month: "Mar", value: 6.4 },
      { month: "Apr", value: 7.8 },
      { month: "May", value: 9.2 },
      { month: "Jun", value: 11.1 },
    ],
    allocations: [
      { label: "Agri-processing", value: "32%" },
      { label: "Irrigation", value: "24%" },
      { label: "AgTech", value: "18%" },
      { label: "Dairy", value: "16%" },
      { label: "Horticulture", value: "10%" },
    ],
  },
  admin: {
    alerts: [
      "3 new projects awaiting ESG review",
      "2 investor profiles pending verification",
      "Quarterly impact report due in 5 days",
    ],
    pendingProjects: [
      {
        name: "Laikipia Solar Irrigation",
        owner: "Amani Cooperative",
        stage: "Series A",
        submitted: "Aug 11, 2024",
        status: "Due diligence",
      },
      {
        name: "Embu Grain Storage",
        owner: "HarvestLink Ltd",
        stage: "Growth",
        submitted: "Aug 03, 2024",
        status: "Impact scoring",
      },
      {
        name: "Kilifi Aqua Farms",
        owner: "BlueEarth Partners",
        stage: "Seed",
        submitted: "Jul 29, 2024",
        status: "Initial review",
      },
    ],
  },
  auth: {
    providers: ["Google", "Microsoft", "LinkedIn"],
    note:
      "Authentication is powered by NextAuth.js (UI stub only in this prototype).",
  },
} as const;
